FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    xvfb xauth x11-utils libx11-6 libxtst6 libxext6 libpng16-16 ffmpeg python3 \
    glslang-tools spirv-tools mesa-vulkan-drivers vulkan-tools vulkan-validationlayers \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /work
